### ISSUE TITLE
Error no file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory D:/comfyui/models/clip\siglip-so400m-patch14-384

### ISSUE THREAD

**Issue by 158zd** [StartHua/Comfyui_CXH_joy_caption#101]
(.venv) PS D:\AI\ComfyUI> python main.py
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-11-14 18:33:57.659128
** Platform: Windows
** Python version: 3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]
** Python executable: D:\AI\ComfyUI\.venv\Scripts\python.exe
** Log path: D:\AI\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   4.6 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8188 MB, total RAM 65416 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: D:\AI\ComfyUI\web
[ComfyUI-Easy-Use] server: v1.2.5 Loaded
[ComfyUI-Easy-Use] web root: D:\AI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\web_version/v2 Loaded
Total VRAM 8188 MB, total RAM 65416 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 : cudaMallocAsync
### Loading: ComfyUI-Impact-Pack (Subpack: V0.8)
[Impact Pack] Wildcards loading done.
### ComfyUI Revision: 2829 [3b9a6cf2] | Released on '2024-11-13'
[comfyui_controlnet_aux] | INFO -> Using ckpts path: D:\AI\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json

Import times for custom nodes:
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI-IC-Light-Native
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI_HF_Servelress_Inference
   0.1 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI-IC-Light
   0.1 seconds: D:\AI\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.5 seconds: D:\AI\ComfyUI\custom_nodes\comfyui_segment_anything
   0.9 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI-Manager
   1.1 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   2.1 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   2.9 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI_LayerStyle

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\AI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
got prompt
clip missing: ['text_projection.weight']
Requested to load FluxClipModel_
Loading 1 new model
loaded completely 0.0 4777.53759765625 True
!!! Exception during processing !!! Error no file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory D:/comfyui/models/clip\siglip-so400m-patch14-384.
Traceback (most recent call last):
  File "D:\AI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)      
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^      
  File "D:\AI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\AI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI_HF_Servelress_Inference\nodes\Joy_Caption.py", line 125, in gen
    self.loadCheckPoint()
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI_HF_Servelress_Inference\nodes\Joy_Caption.py", line 84, in loadCheckPoint
    clip_model = AutoModel.from_pretrained(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\.venv\Lib\site-packages\transformers\models\auto\auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\.venv\Lib\site-packages\transformers\modeling_utils.py", line 3763, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory D:/comfyui/models/clip\siglip-so400m-patch14-384.

Prompt executed in 9.92 seconds
Computer: Windows 10, transformers: 4.46.2

**Comment by Susi99** [comment]
here is easy solution : "D:/comfyui/models/clip\siglip-so400m-patch14-384" or where your file located at, delete all files here and try open again

**Comment by Susi99** [comment]
it will download files and will be fixed

**Comment by Diogovidro33** [comment]
@Susi99 what does this part means? "glip-so400m-patch14-384"
