### ISSUE TITLE
Expected `device_type` of type `str`, got: `<class 'torch.device'>`

### ISSUE THREAD

**Issue by langbowang** [StartHua/Comfyui_CXH_joy_caption#36]
![image](https://github.com/user-attachments/assets/67ca0bad-8798-4aa2-a249-44b379104de8)

# ComfyUI Error Report
## Error Details
- **Node Type:** Joy_caption
- **Exception Type:** ValueError
- **Exception Message:** Expected `device_type` of type `str`, got: `<class 'torch.device'>`
## Stack Trace
```
  File "C:\Users\lbw\AIGC\ComfyUI_FluxFast\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\lbw\AIGC\ComfyUI_FluxFast\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\lbw\AIGC\ComfyUI_FluxFast\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\Users\lbw\AIGC\ComfyUI_FluxFast\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\lbw\AIGC\ComfyUI_FluxFast\ComfyUI\custom_nodes\ComfyUI_HF_Servelress_Inference\nodes\Joy_Caption.py", line 171, in gen
    with torch.amp.autocast_mode.autocast(DEVICE, enabled=True):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\lbw\AIGC\ComfyUI_FluxFast\python_embeded\Lib\site-packages\torch\amp\autocast_mode.py", line 225, in __init__
    raise ValueError(

**Comment by langbowang** [comment]
![image](https://github.com/user-attachments/assets/02b21471-3965-45be-84b0-d2adde40b64c)

`got prompt                                                                                                                    
Unused kwargs: ['_load_in_4bit', '_load_in_8bit', 'quant_method']. These kwargs are not used in <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>.                                                                                        
We will use 90% of the memory on device 0 for storing the model, and 10% for the buffer to avoid OOM. You can set `max_memory` in to a higher value to use more memory (at your own risk).                                                                  
C:\Users\lbw\AIGC\ComfyUI_FluxFast\ComfyUI\custom_nodes\ComfyUI_HF_Servelress_Inference\nodes\Joy_Caption.py:107: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.                        
  image_adapter.load_state_dict(torch.load(adapter_path, map_location="cpu"))                                                 
!!! Exception during processing !!! Expected `device_type` of type `str`, got: `<class 'torch.device'>`                       
Traceback (most recent call last):                                                                                            
  File "C:\Users\lbw\AIGC\ComfyUI_FluxFast\ComfyUI\execution.py", line 317, in execute                                        
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)                                                                                                       
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                       
  File "C:\Users\lbw\AIGC\ComfyUI_FluxFast\ComfyUI\execution.py", line 192, in get_output_data                                
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)                                                                                      
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                      
  File "C:\Users\lbw\AIGC\ComfyUI_FluxFast\ComfyUI\execution.py", line 169, in _map_node_over_list                            
    process_inputs(input_dict, i)                                                                                             
  File "C:\Users\lbw\AIGC\ComfyUI_FluxFast\ComfyUI\execution.py", line 158, in process_inputs                                 
    results.append(getattr(obj, func)(**inputs))                                                                              
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                               
  File "C:\Users\lbw\AIGC\ComfyUI_FluxFast\ComfyUI\custom_nodes\ComfyUI_HF_Servelress_Inference\nodes\Joy_Caption.py", line 171, in gen                                                                                                                     
    with torch.amp.autocast_mode.autocast(DEVICE, enabled=True):                                                              
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                               
  File "C:\Users\lbw\AIGC\ComfyUI_FluxFast\python_embeded\Lib\site-packages\torch\amp\autocast_mode.py", line 225, in __init__
    raise ValueError(                                                                                                         
ValueError: Expected `device_type` of type `str`, got: `<class 'torch.device'>` `

**Comment by mirek190** [comment]
Joy_caption
Expected `device_type` of type `str`, got: `<class 'torch.device'>`



The same error 


If you switch off Joy_caption and leave Florence 2 and MiniCPM v2_6 then works.
Seems error causing only  Joy_caption node.

**Comment by qtnrtnd** [comment]
yep, same problem here

**Comment by train147369** [comment]
同样错误，双gpu

**Comment by qtnrtnd** [comment]
It worked for me when integrating the changes of #23  in ComfyUI\custom_nodes\ComfyUI_HF_Servelress_Inference\nodes\Joy_Caption.py

**Comment by train147369** [comment]
D:\AIProject\ComfyUI\custom_nodes\ComfyUI_HF_Servelress_Inference\nodes\
找到这一行：
pythonCopywith torch.amp.autocast_mode.autocast(DEVICE, enabled=True):

将其更改为：
pythonCopywith torch.amp.autocast_mode.autocast(DEVICE.type if isinstance(DEVICE, torch.device) else DEVICE, enabled=True):
