### ISSUE TITLE
No module named 'matplotlib'

### ISSUE THREAD

**Issue by azumukupoe** [StartHua/Comfyui_CXH_joy_caption#55]
I think it's just missing from the requirements.txt
```
Traceback (most recent call last):
  File "C:\SD\ComfyUI\nodes.py", line 1994, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\SD\ComfyUI\custom_nodes\Comfyui_CXH_joy_caption\__init__.py", line 5, in <module>
    from .florence_nodes import CXH_DownloadAndLoadFlorence2Model,CXH_Florence2Run
  File "C:\SD\ComfyUI\custom_nodes\Comfyui_CXH_joy_caption\florence_nodes.py", line 9, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'

Cannot import C:\SD\ComfyUI\custom_nodes\Comfyui_CXH_joy_caption module for custom nodes: No module named 'matplotlib'
```

**Comment by tanzai** [comment]
你这个问题很好解决，安装一下matplotlib包就可以，命令：python.exe -m pip install matplotlib
