### ISSUE TITLE
 This error originates from a subprocess, and is likely not a problem with pip.

### ISSUE THREAD

**Issue by kuzhushidai** [StartHua/Comfyui_CXH_joy_caption#61]
Collecting huggingface_hub==0.24.3 (from -r F:\ComfyUI-aki-v1.2\custom_nodes\Comfyui_CXH_joy_caption\requirements.txt (line 1))
  Using cached huggingface_hub-0.24.3-py3-none-any.whl.metadata (13 kB)
Collecting transformers>=4.44.2 (from -r F:\ComfyUI-aki-v1.2\custom_nodes\Comfyui_CXH_joy_caption\requirements.txt (line 2))
  Using cached transformers-4.44.2-py3-none-any.whl.metadata (43 kB)
Collecting tqdm (from -r F:\ComfyUI-aki-v1.2\custom_nodes\Comfyui_CXH_joy_caption\requirements.txt (line 3))
  Using cached tqdm-4.66.5-py3-none-any.whl.metadata (57 kB)
Collecting numpy (from -r F:\ComfyUI-aki-v1.2\custom_nodes\Comfyui_CXH_joy_caption\requirements.txt (line 4))
  Using cached numpy-2.1.1-cp312-cp312-win_amd64.whl.metadata (59 kB)
Collecting surrealist (from -r F:\ComfyUI-aki-v1.2\custom_nodes\Comfyui_CXH_joy_caption\requirements.txt (line 5))
  Using cached surrealist-0.5.3-py3-none-any.whl.metadata (31 kB)
Collecting boto3==1.34.86 (from -r F:\ComfyUI-aki-v1.2\custom_nodes\Comfyui_CXH_joy_caption\requirements.txt (line 6))
  Using cached boto3-1.34.86-py3-none-any.whl.metadata (6.6 kB)
Collecting llama-cpp-python==0.2.89 (from -r F:\ComfyUI-aki-v1.2\custom_nodes\Comfyui_CXH_joy_caption\requirements.txt (line 7))
  Using cached llama_cpp_python-0.2.89.tar.gz (64.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting Pillow==10.1.0 (from -r F:\ComfyUI-aki-v1.2\custom_nodes\Comfyui_CXH_joy_caption\requirements.txt (line 8))
  Using cached Pillow-10.1.0-cp312-cp312-win_amd64.whl.metadata (9.6 kB)
Collecting sentencepiece==0.1.99 (from -r F:\ComfyUI-aki-v1.2\custom_nodes\Comfyui_CXH_joy_caption\requirements.txt (line 9))
  Using cached sentencepiece-0.1.99.tar.gz (2.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      Traceback (most recent call last):
        File "C:\Users\83784\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\83784\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\83784\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\83784\AppData\Local\Temp\pip-build-env-b6zr376a\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\83784\AppData\Local\Temp\pip-build-env-b6zr376a\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "C:\Users\83784\AppData\Local\Temp\pip-build-env-b6zr376a\overlay\Lib\site-packages\setuptools\build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\83784\AppData\Local\Temp\pip-build-env-b6zr376a\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 126, in <module>
        File "C:\Users\83784\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 408, in check_call
          retcode = call(*popenargs, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\83784\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 389, in call
          with Popen(*popenargs, **kwargs) as p:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\83784\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\83784\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [WinError 2] 系统找不到指定的文件。
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

大佬问一下 我更新了python版本后继续安装就这样了 麻烦帮忙看看 为啥会按照失败

**Comment by lwn1989** [comment]
一样的问题，大佬你解决了吗
