### ISSUE TITLE
This modeling file requires the following packages that were not found in your environment: flash_attn. Run `pip install flash_attn`

### ISSUE THREAD

**Issue by mr-bob-chang** [StartHua/Comfyui_CXH_joy_caption#91]
大佬，运行CXH_DownloadAndLoadFlorence2Model这个节点会报错，说是缺少flash_attn这个东西。

# ComfyUI Error Report
## Error Details
- **Node Type:** CXH_DownloadAndLoadFlorence2Model
- **Exception Type:** ImportError
- **Exception Message:** This modeling file requires the following packages that were not found in your environment: flash_attn. Run `pip install flash_attn`
## Stack Trace
```
  File "E:\ComfyUI_windows_portable-b\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\ComfyUI_windows_portable-b\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\ComfyUI_windows_portable-b\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "E:\ComfyUI_windows_portable-b\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\ComfyUI_windows_portable-b\ComfyUI\custom_nodes\Comfyui_CXH_joy_caption\florence_nodes.py", line 92, in loadmodel
    model = AutoModelForCausalLM.from_pretrained(model_path, attn_implementation=attention, device_map=device, torch_dtype=dtype,trust_remote_code=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\ComfyUI_windows_portable-b\python_embeded\Lib\site-packages\transformers\models\auto\auto_factory.py", line 551, in from_pretrained
    model_class = get_class_from_dynamic_module(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\ComfyUI_windows_portable-b\python_embeded\Lib\site-packages\transformers\dynamic_module_utils.py", line 502, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
                   ^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\ComfyUI_windows_portable-b\python_embeded\Lib\site-packages\transformers\dynamic_module_utils.py", line 327, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\ComfyUI_windows_portable-b\python_embeded\Lib\site-packages\transformers\dynamic_module_utils.py", line 182, in check_imports
    raise ImportError(





然后我用pip install flash_attn安装这个环境，得到了下面的报错

C:\Users\Hard_Core>pip install flash_attn
Collecting flash_attn
  Using cached flash_attn-2.6.3.tar.gz (2.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Hard_Core\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Hard_Core\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Hard_Core\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Hard_Core\AppData\Local\Temp\pip-build-env-47_ilwp5\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "C:\Users\Hard_Core\AppData\Local\Temp\pip-build-env-47_ilwp5\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "C:\Users\Hard_Core\AppData\Local\Temp\pip-build-env-47_ilwp5\overlay\Lib\site-packages\setuptools\build_meta.py", line 516, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\Hard_Core\AppData\Local\Temp\pip-build-env-47_ilwp5\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 21, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

请问这个是怎么回事呢？

**Comment by liutianping** [comment]
Windows系统的话，显卡要30系以上才能装。20系的显卡是图灵架构，在Windows不支持flash_attn。

**Comment by mr-bob-chang** [comment]
> Windows系统的话，显卡要30系以上才能装。20系的显卡是图灵架构，在Windows不支持flash_attn。

我的显卡是4090

**Comment by biu5332** [comment]
你好，我也遇到了同样的问题，请问你解决该问题了吗

**Comment by sd2530615** [comment]
win10,4080,同样的问题
